/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    immobilien: Immobilien;
    referenzen: Referenzen;
    makler: Makler;
    anfragen: Anfragen;
    termine: Termine;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    immobilien: ImmobilienSelect<false> | ImmobilienSelect<true>;
    referenzen: ReferenzenSelect<false> | ReferenzenSelect<true>;
    makler: MaklerSelect<false> | MaklerSelect<true>;
    anfragen: AnfragenSelect<false> | AnfragenSelect<true>;
    termine: TermineSelect<false> | TermineSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    home: Home;
    unternehmen: Unternehman;
    impressum: Impressum;
    datenschutz: Datenschutz;
    agb: Agb;
    widerruf: Widerruf;
    cookies: Cooky;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    unternehmen: UnternehmenSelect<false> | UnternehmenSelect<true>;
    impressum: ImpressumSelect<false> | ImpressumSelect<true>;
    datenschutz: DatenschutzSelect<false> | DatenschutzSelect<true>;
    agb: AgbSelect<false> | AgbSelect<true>;
    widerruf: WiderrufSelect<false> | WiderrufSelect<true>;
    cookies: CookiesSelect<false> | CookiesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Editor kann Inhalte pflegen, Admin verwaltet System & Benutzer. Makler kann Immobilien anlegen und bearbeiten.
   */
  role: 'admin' | 'editor' | 'makler';
  /**
   * Verknüpftes Makler-Profil (nur bei Rolle "Makler" relevant).
   */
  maklerProfile?: (number | null) | Makler;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Ansprechpartner & Makler verwalten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makler".
 */
export interface Makler {
  id: number;
  name: string;
  /**
   * z.B. "Immobilienberater" oder "Projektentwicklung"
   */
  titleRole?: string | null;
  phone?: string | null;
  email?: string | null;
  photo?: (number | null) | Media;
  /**
   * z.B. "Mo–Fr 9–18 Uhr"
   */
  availability?: string | null;
  /**
   * z.B. "Schlüsselfertig", "Kauf ab Plan", "Kapitalanlage"
   */
  focus?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Login-Account des Maklers (nur Admin sichtbar).
   */
  linkedUser?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Wichtig für Barrierefreiheit & SEO (bei Bildern).
   */
  alt: string;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Immobilien verwalten: anlegen, bearbeiten, veröffentlichen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "immobilien".
 */
export interface Immobilien {
  id: number;
  title: string;
  /**
   * Wird automatisch aus dem Titel erzeugt (kann angepasst werden).
   */
  slug: string;
  vermarktungsStatus: 'verfuegbar' | 'reserviert' | 'verkauft' | 'in_bau';
  location: string;
  /**
   * Leer lassen = „Preis auf Anfrage“.
   */
  price?: number | null;
  livingArea?: number | null;
  plotArea?: number | null;
  rooms?: number | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  yearBuilt?: number | null;
  availability?: string | null;
  /**
   * Kleine Zusatzinfo im Header (z. B. „Neubau“).
   */
  badge?: string | null;
  /**
   * Makler, der auf der Objektseite angezeigt wird.
   */
  ansprechpartner?: (number | null) | Makler;
  heroMedia?: (number | null) | Media;
  gallery?:
    | {
        item: number | Media;
        id?: string | null;
      }[]
    | null;
  documents?: {
    exposePdf?: (number | null) | Media;
  };
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  energy?: {
    certificateType?: ('bedarf' | 'verbrauch') | null;
    value?: number | null;
    class?: string | null;
    carrier?: string | null;
    year?: number | null;
  };
  buyerCommission: {
    kind: 'percent' | 'fixed';
    value: number;
    vatIncluded?: boolean | null;
    vatRate?: number | null;
    due?: string | null;
    basis?: string | null;
    note?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Referenzprojekte verwalten: Neubau, Sanierung, Verkauf, Projektentwicklung.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referenzen".
 */
export interface Referenzen {
  id: number;
  title: string;
  /**
   * Wird automatisch aus dem Titel erzeugt (kann angepasst werden).
   */
  slug: string;
  subtitle?: string | null;
  category: 'Neubau' | 'Sanierung' | 'Projektentwicklung' | 'Verkauf' | 'Kapitalanlage' | 'Gewerbe';
  year: string;
  /**
   * Featured Projekte erscheinen zuerst.
   */
  isFeatured?: boolean | null;
  /**
   * Höhere Zahl = weiter oben.
   */
  sortOrder?: number | null;
  location?: {
    region?: string | null;
    label?: string | null;
    geo?: {
      lat?: number | null;
      lng?: number | null;
    };
  };
  description: string;
  /**
   * Kurze Schlagworte für Karten und Hero.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        item: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  documents?: {
    caseStudyPdf?: (number | null) | Media;
    exposeSample?: (number | null) | Media;
    brochure?: (number | null) | Media;
  };
  facts?: {
    units?: string | null;
    livingArea?: string | null;
    plotArea?: string | null;
    rooms?: string | null;
    buildTime?: string | null;
    status?: ('fertiggestellt' | 'verkauft' | 'reserviert' | 'in bau') | null;
  };
  kpis?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  services?:
    | (
        | 'Projektentwicklung'
        | 'Bauträger'
        | 'Vermarktung'
        | 'Sanierung'
        | 'Architektur'
        | 'Innenausbau'
        | 'Finishing'
        | 'Fotografie'
        | 'Branding'
        | 'UI/Website'
      )[]
    | null;
  timeline?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        heading: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  caseStudy?: {
    challenge?: string | null;
    approach?: string | null;
    result?: string | null;
  };
  testimonial?: {
    quote?: string | null;
    author?: string | null;
    role?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Eingehende Kontaktanfragen vom Website-Formular.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anfragen".
 */
export interface Anfragen {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  contactPreference?: ('telefon' | 'email') | null;
  topic?: ('allgemein' | 'expose' | 'kaufen' | 'neubau' | 'verkauf') | null;
  message?: string | null;
  callbackRequested?: boolean | null;
  preferredDate?: string | null;
  preferredTimeWindow?: ('09-12' | '12-15' | '15-18' | '18-20') | null;
  preferredTime?: string | null;
  durationMinutes?: number | null;
  /**
   * Zugehörige Immobilie (optional)
   */
  listing?: (number | null) | Immobilien;
  /**
   * Automatisch vom Kontaktformular übernommener Titel.
   */
  listingTitle?: string | null;
  status?: ('neu' | 'gelesen' | 'kontaktiert' | 'termin_vereinbart' | 'bearbeitet' | 'archiviert') | null;
  assignedMakler?: (number | null) | Makler;
  internalNotes?: string | null;
  receivedAt?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Besichtigungstermine und Kundentermine verwalten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "termine".
 */
export interface Termine {
  id: number;
  date: string;
  /**
   * Format: HH:MM (z.B. 09:00)
   */
  startTime: string;
  /**
   * z.B. 30, 60, 90
   */
  durationMinutes?: number | null;
  timezone?: string | null;
  /**
   * Zuständiger Makler für diesen Termin
   */
  makler: number | Makler;
  /**
   * Besichtigungsobjekt (falls zutreffend)
   */
  listing?: (number | null) | Immobilien;
  customerName: string;
  customerEmail: string;
  customerPhone?: string | null;
  customerMessage?: string | null;
  /**
   * Nur intern sichtbar
   */
  internalNotes?: string | null;
  /**
   * Zugehörige Kontaktanfrage, aus der dieser Termin entstand (optional)
   */
  sourceAnfrage?: (number | null) | Anfragen;
  status?: ('geplant' | 'bestaetigt' | 'absolviert' | 'storniert') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'immobilien';
        value: number | Immobilien;
      } | null)
    | ({
        relationTo: 'referenzen';
        value: number | Referenzen;
      } | null)
    | ({
        relationTo: 'makler';
        value: number | Makler;
      } | null)
    | ({
        relationTo: 'anfragen';
        value: number | Anfragen;
      } | null)
    | ({
        relationTo: 'termine';
        value: number | Termine;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  maklerProfile?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "immobilien_select".
 */
export interface ImmobilienSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  vermarktungsStatus?: T;
  location?: T;
  price?: T;
  livingArea?: T;
  plotArea?: T;
  rooms?: T;
  bedrooms?: T;
  bathrooms?: T;
  yearBuilt?: T;
  availability?: T;
  badge?: T;
  ansprechpartner?: T;
  heroMedia?: T;
  gallery?:
    | T
    | {
        item?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        exposePdf?: T;
      };
  description?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  energy?:
    | T
    | {
        certificateType?: T;
        value?: T;
        class?: T;
        carrier?: T;
        year?: T;
      };
  buyerCommission?:
    | T
    | {
        kind?: T;
        value?: T;
        vatIncluded?: T;
        vatRate?: T;
        due?: T;
        basis?: T;
        note?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referenzen_select".
 */
export interface ReferenzenSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  category?: T;
  year?: T;
  isFeatured?: T;
  sortOrder?: T;
  location?:
    | T
    | {
        region?: T;
        label?: T;
        geo?:
          | T
          | {
              lat?: T;
              lng?: T;
            };
      };
  description?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  coverImage?: T;
  gallery?:
    | T
    | {
        item?: T;
        alt?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        caseStudyPdf?: T;
        exposeSample?: T;
        brochure?: T;
      };
  facts?:
    | T
    | {
        units?: T;
        livingArea?: T;
        plotArea?: T;
        rooms?: T;
        buildTime?: T;
        status?: T;
      };
  kpis?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  services?: T;
  timeline?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        content?: T;
        id?: T;
      };
  caseStudy?:
    | T
    | {
        challenge?: T;
        approach?: T;
        result?: T;
      };
  testimonial?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makler_select".
 */
export interface MaklerSelect<T extends boolean = true> {
  name?: T;
  titleRole?: T;
  phone?: T;
  email?: T;
  photo?: T;
  availability?: T;
  focus?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  linkedUser?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anfragen_select".
 */
export interface AnfragenSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  contactPreference?: T;
  topic?: T;
  message?: T;
  callbackRequested?: T;
  preferredDate?: T;
  preferredTimeWindow?: T;
  preferredTime?: T;
  durationMinutes?: T;
  listing?: T;
  listingTitle?: T;
  status?: T;
  assignedMakler?: T;
  internalNotes?: T;
  receivedAt?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "termine_select".
 */
export interface TermineSelect<T extends boolean = true> {
  date?: T;
  startTime?: T;
  durationMinutes?: T;
  timezone?: T;
  makler?: T;
  listing?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  customerMessage?: T;
  internalNotes?: T;
  sourceAnfrage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Zentrale Daten für Footer, Kontakt, Branding und Socials.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  /**
   * Nur Anzeige/Info. Farben werden im Frontend gesetzt.
   */
  accentLabel?: string | null;
  company: string;
  addressLine1?: string | null;
  addressLine2?: string | null;
  phone?: string | null;
  email?: string | null;
  whatsapp?: string | null;
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerHeadline?: string | null;
  footerText?: string | null;
  legalLinksHint?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Inhalte der Startseite: Hero, USPs, Sektionen, CTA.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  badge?: string | null;
  headline?: {
    before?: string | null;
    highlight?: string | null;
    after?: string | null;
  };
  subline?: {
    text?: string | null;
    highlight?: string | null;
  };
  trustPills?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  scrollHint?: string | null;
  heroVideo?: {
    src?: string | null;
    type?: string | null;
  };
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  infoSections?:
    | {
        title: string;
        text: string;
        icon?: ('shield' | 'sparkles' | 'home' | 'map') | null;
        id?: string | null;
      }[]
    | null;
  ctaBlock?: {
    title?: string | null;
    text?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Unternehmensseite: Hero, Highlights, Prozess, Werte, Zahlen, CTA.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unternehmen".
 */
export interface Unternehman {
  id: number;
  badge?: string | null;
  headlineTop?: string | null;
  headlineMuted?: string | null;
  headlineGradient?: string | null;
  description?: string | null;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  heroCards?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  heroImages?: {
    a?: (number | null) | Media;
    b?: (number | null) | Media;
    c?: (number | null) | Media;
    d?: (number | null) | Media;
  };
  highlightsTitle?: string | null;
  highlightsDescription?: string | null;
  highlightsImage?: (number | null) | Media;
  highlightsBullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  processTitle?: string | null;
  processDescription?: string | null;
  steps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  pillarsTitle?: string | null;
  pillarsDescription?: string | null;
  pillars?:
    | {
        icon: 'Building' | 'Sparkles' | 'Home' | 'FileCheck2';
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        icon?: ('Building2' | 'ShieldCheck' | 'Scale' | 'Handshake') | null;
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  ctaPrimaryLabel?: string | null;
  ctaPrimaryHref?: string | null;
  ctaSecondaryLabel?: string | null;
  ctaSecondaryHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Strukturierte Pflichtangaben gemaß § 5 TMG. Alle Felder erscheinen direkt auf der Impressum-Seite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum".
 */
export interface Impressum {
  id: number;
  company: string;
  streetAddress?: string | null;
  city?: string | null;
  country?: string | null;
  ceo?: string | null;
  /**
   * Gemäß § 55 Abs. 2 RStV. Leer lassen wenn identisch mit Geschäftsführer.
   */
  responsible?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Zuständiges Handelsregistergericht.
   */
  registergericht?: string | null;
  hrb?: string | null;
  /**
   * Umsatzsteuer-Identifikationsnummer gemäß § 27a UStG. Leer lassen falls noch nicht vorhanden.
   */
  ustId?: string | null;
  /**
   * Nur ausfüllen wenn Immobilienmakler-Tätigkeit nach § 34c GewO ausgeführt wird (was hier der Fall ist).
   */
  gewo34cText?: string | null;
  /**
   * Optionaler Freitext zur Verbraucherschlichtung. Standard-Text wird angezeigt wenn leer.
   */
  streitbeilegung?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Datum der letzten inhaltlichen Änderung (z.B. "23.02.2026").
   */
  lastUpdated?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Datenschutzerklärung Inhalte (DE).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutz".
 */
export interface Datenschutz {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Falls ein Datenschutzbeauftragter bestellt ist, hier eintragen.
   */
  dpo?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Allgemeine Geschäftsbedingungen (DE).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agb".
 */
export interface Agb {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Widerrufsbelehrung (DE).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "widerruf".
 */
export interface Widerruf {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Cookie-Infos (DE).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookies".
 */
export interface Cooky {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  tagline?: T;
  logo?: T;
  accentLabel?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  phone?: T;
  email?: T;
  whatsapp?: T;
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerHeadline?: T;
  footerText?: T;
  legalLinksHint?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  badge?: T;
  headline?:
    | T
    | {
        before?: T;
        highlight?: T;
        after?: T;
      };
  subline?:
    | T
    | {
        text?: T;
        highlight?: T;
      };
  trustPills?:
    | T
    | {
        text?: T;
        id?: T;
      };
  scrollHint?: T;
  heroVideo?:
    | T
    | {
        src?: T;
        type?: T;
      };
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  infoSections?:
    | T
    | {
        title?: T;
        text?: T;
        icon?: T;
        id?: T;
      };
  ctaBlock?:
    | T
    | {
        title?: T;
        text?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unternehmen_select".
 */
export interface UnternehmenSelect<T extends boolean = true> {
  badge?: T;
  headlineTop?: T;
  headlineMuted?: T;
  headlineGradient?: T;
  description?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  heroCards?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  heroImages?:
    | T
    | {
        a?: T;
        b?: T;
        c?: T;
        d?: T;
      };
  highlightsTitle?: T;
  highlightsDescription?: T;
  highlightsImage?: T;
  highlightsBullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  processTitle?: T;
  processDescription?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  pillarsTitle?: T;
  pillarsDescription?: T;
  pillars?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        icon?: T;
        value?: T;
        label?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaDescription?: T;
  ctaPrimaryLabel?: T;
  ctaPrimaryHref?: T;
  ctaSecondaryLabel?: T;
  ctaSecondaryHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum_select".
 */
export interface ImpressumSelect<T extends boolean = true> {
  company?: T;
  streetAddress?: T;
  city?: T;
  country?: T;
  ceo?: T;
  responsible?: T;
  phone?: T;
  email?: T;
  registergericht?: T;
  hrb?: T;
  ustId?: T;
  gewo34cText?: T;
  streitbeilegung?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutz_select".
 */
export interface DatenschutzSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  dpo?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agb_select".
 */
export interface AgbSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "widerruf_select".
 */
export interface WiderrufSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookies_select".
 */
export interface CookiesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}